In [1]:
import numpy as np

In [2]:
X = np.array([
    [9,11,10],
    [2,2,1],
    [10,9,11],
    [3,2,1],
    [11,10,9],
    [1,3,3]
])

Y = np.array([
    [-1],
    [1],
    [-1],
    [1],
    [-1],
    [1]
])

In [3]:
w = np.array([0,0,0])
n_epochs = 1
lr = 0.1

for i in range(n_epochs):
    for x, y in zip(X,Y):
        yhat = 0
        dotp = x @ w
        
        if dotp <= 0:
            yhat = -1
        else:
            yhat = 1
            
        w = w + (x * (y - yhat))
        
    
print(w, x, y, yhat)
        

3
3
1

3
3
1

3
3
1

3
3
1

3
3
1

3
3
1

[ -8  -4 -12] [1 3 3] [1] -1


In [4]:
for train_sample, train_label in zip(X,Y):
    if np.matmul(train_sample, w) <= 0:
        label_hat = -1
    else:
        label_hat = 1

    print(train_sample)
    print(f'Predicted label: {label_hat}')
    print(f'Real label: {train_label[0]}')
    print()



[ 9 11 10]
Predicted label: -1
Real label: -1

[2 2 1]
Predicted label: -1
Real label: 1

[10  9 11]
Predicted label: -1
Real label: -1

[3 2 1]
Predicted label: -1
Real label: 1

[11 10  9]
Predicted label: -1
Real label: -1

[1 3 3]
Predicted label: -1
Real label: 1



In [ ]:
X_test = np.array([
    [10,10,10],
    [2,3,2],
    [8,9,8],
    [3,3,0],
    [11,12,13],
    [1,1,-1]
])

Y_test = np.array([
    [-1],
    [1],
    [-1],
    [1],
    [-1],
    [1]
])

for test_sample, test_label in zip(X_test,Y_test):
    if np.matmul(test_sample, w) <= 0:
        label_hat = -1
    else:
        label_hat = 1

    print(test_sample)
    print(f'Predicted label: {label_hat}')
    print(f'Real label: {test_label[0]}')
    print()

